name: snowpark
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - 'snowflake_snowpark_python-0.4.0-py3-none-any.whl'
      - pandas_profiling
      - snowflake-snowpark-python

